#!/usr/bin/env python

import sys
import os

path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if os.path.exists(os.path.join(path, 'setup.py')):
    sys.path.insert(0, path)

import validatorcrawler

if __name__ == '__main__':
    validatorcrawler.main()
